[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino, espidf
monitor_speed = 115200
upload_speed = 921600
board_build.sdkconfig_defaults = sdkconfig.defaults

; SD + SPI are part of Arduino-ESP32 core and are used via #include <SD.h> and #include <SPI.h>
; GPS is read from SIM7600G GNSS via AT commands.
lib_deps =
