[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 57600
board_build.sdkconfig_defaults = sdkconfig.defaults
build_flags =
	-Iinclude
extra_scripts =
	pre:tools/force_upload_transport.py
	post:tools/make_resqlink_elf.py

; upload_flags =
;     --no-stub


; SD + SPI are part of Arduino-ESP32 core and are used via #include <SD.h> and #include <SPI.h>
; GPS is read from SIM7600G GNSS via AT commands.
lib_deps =
